### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by ChrisChinchilla** [vale-cli/vale-action#2]
Tried the action on a repository, to begin with copying the setup for the example repository you link to, which results in the following error - https://github.com/EventStore/documentation/pull/386/checks?check_run_id=285272315

I feel like I've seen this before. But I tested running the command the action is trying to run locally, and Vale runs successfully. GitHub Actions are really hard to debug, but maybe you saw something like this when testing.

**Comment by jdkato** [comment]
Thanks for the report.

I think I've finally figured this out (it appears in VS Code occasionally too): the [`child_process`](https://nodejs.org/api/child_process.html) library truncates output whenever it exceeds a certain length (which happens when Vale finds a lot of alerts) and that results in invalid JSON.

This *should* be fixed in `v1.0.1`.

**Comment by ChrisChinchilla** [comment]
Ahh Nice. That's where I'd seen the error before too, the VSC extension :)
